name: example
description: A new Flutter project.
publish_to: 'none'
version: 0.3.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloudpayments:
    path: ../

  flutter_svg: ^0.22.0
  mask_text_input_formatter: ^2.0.0-nullsafety.2
  dio: ^4.0.0
  loading_overlay: ^0.3.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  talker: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true