name: cloudpayments
description: A Flutter plugin for integrating Cloudpaymanets in Android and iOS applications.
version: 0.3.0
repository: https://github.com/shushper/cloudpayments

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  json_annotation: ^4.4.0
  pretty_dio_logger: ^1.1.1

dev_dependencies:
  build_runner:
  json_serializable: ^6.1.5
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.shushper.cloudpayments
        pluginClass: CloudpaymentsPlugin
      ios:
        pluginClass: CloudpaymentsPlugin

